# Check to see if newer versions are available
##############################################
# $ docker-compose pull
# $ docker-compose pull <specific_app> 

# Run docker compose file
#########################
# $ docker-compose up -d
# $ docker-compose down 

services:
  my_sql:
  # container_name
    image: portfedh/portfolio_dashboard:clg_mysql
    ports:
      - "3306:3306"
    # host:container
    volumes:
      - my_sql_DB_clg:/var/lib/mysql/
      # Host_directory_name:Container_directory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1
  grafana:
    image: portfedh/portfolio_dashboard:clg_grafana
    ports:
      - "3000:3000"
    restart: always
volumes:
  my_sql_DB: